name: ros-ci
on: [pull_request]
jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@0.2.1
      - uses: ros-tooling/action-ros-ci@0.2.1
        with:
          package-name: uuv2_gazebo_world_plugins
          target-ros2-distro: foxy