name: ament_lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, copyright, cpplint, cppcheck, uncrustify, flake8, pep257, pycodestyle]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.2.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: uuv2_gazebo_world_plugins